name: CI
on: [push, pull_request]
jobs:
  test-elixir:
    runs-on: ubuntu-latest
    container:
      image: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-alpine-3.12.0
      env:
        ELIXIR_ASSERT_TIMEOUT: 2000

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.9.4
            otp: 20.3.8.26
          - elixir: 1.11.0-rc.0
            otp: 21.3.8.17
          - elixir: 1.11.0-rc.0
            otp: 23.0.4
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          apk add --no-progress --update git
          mix deps.get
      - run: mix test
      - name: Run installer tests
        run: mix test
        working-directory: installer
      # - run: MIX_ENV=docs mix inch.report

  npm_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.4
        with:
          otp-version: 23.0.4
          elixir-version: 1.11.0-rc.0
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.16
      - name: npm install and test
        run: |
          cd assets
          npm install
          npm test
