name: CI
on: [push, pull_request]
jobs:
  test-elixir:
    runs-on: ubuntu-latest
    container:
      image: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-alpine-3.12.0
      env:
        ELIXIR_ASSERT_TIMEOUT: 2000

    strategy:
      fail-fast: false
      matrix:
        include:
          - elixir: 1.9.4
            otp: 20.3.8.26
          - elixir: 1.10.4
            otp: 21.3.8.17
          - elixir: 1.10.4
            otp: 23.0.3
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          apk add --no-progress --update git
          mix deps.get
      - run: mix test
      - name: Run installer tests
        run: mix test
        working-directory: installer
      # - run: MIX_ENV=docs mix inch.report

  integration-test-elixir:
    runs-on: ubuntu-latest
    container:
      image: hexpm/elixir:${{ matrix.elixir }}-erlang-${{ matrix.otp }}-alpine-3.12.0
      env:
        ELIXIR_ASSERT_TIMEOUT: 2000
    env:
      CACHE_VERSION: 1

    strategy:
      fail-fast: false
      matrix:
        include:
          # Can't run integration tests before OTP 20.2 due to incompatiblity with cowlib.
          #
          # See https://github.com/phoenixframework/phoenix/issues/3903
          - elixir: 1.9.4
            otp: 21.2.7
          - elixir: 1.10.4
            otp: 21.3.8.17
          - elixir: 1.10.4
            otp: 23.0.3
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Install Dependencies
        # Tar needs to be installed so actions/cache works properly
        run: |
          mix local.rebar --force
          mix local.hex --force
          apk add --no-progress --update git tar
          mix deps.get
      # This is used with the next step to ensure a cache is stored each time
      - name: Get timestamp for cache key
        id: timestamp-for-cache-key
        run: |
          echo "::set-output name=timestamp::$(/bin/date -u "+%s")"
      - uses: actions/cache@v2
        with:
          path: tmp/integration_cache/build
          key: ${{ env.CACHE_VERSION }}-integration_cache-${{ matrix.otp }}-${{ matrix.elixir }}-${{ steps.timestamp-for-cache-key.outputs.timestamp }}
          restore-keys: |
            ${{ env.CACHE_VERSION }}-integration_cache-${{ matrix.otp }}-${{ matrix.elixir }}-
      - name: Run integration tests
        run: mix test.integration

  npm_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: actions/setup-elixir@v1.3.0
        with:
          otp-version: 23.0.3
          elixir-version: 1.10.4
      - name: Install Dependencies
        run: |
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.1
        with:
          node-version: 12.16
      - name: npm install and test
        run: |
          cd assets
          npm install
          npm test
